### ISSUE TITLE
Jmx4Perl with authenticaiton for jolokia 1.6 - duplicate http requests

### ISSUE THREAD

**Issue by erempel** [rhuss/jolokia#417] opened 2019-09-26 16:15 UTC
jmx4perl 1.12 
jolokia WAR-Agent 1.6.2 

I'm having difficulty using the Jmx4Perl library to access the secured jolokia WAR-Agent. The access logs show that the http request is first performed without authenticaiton, and then immediately repeated with the authentication. 

127.0.0.1 - - [21/Sep/2019:00:00:07] "GET /jolokia/read/java.lang%3Atype%3DThreading/ThreadCount HTTP/1.1" 401 1034 
127.0.0.1 - uvstats [21/Sep/2019:00:00:07] "GET /jolokia/read/java.lang%3Atype%3DThreading/ThreadCount HTTP/1.1" 200 146 

I am creating a JMX::Jmx4Perl object with 

$jmx = JMX::Jmx4Perl->new( 
    product => 'tomcat', 
    url => "http://localhost:8080/jolokia", 
    user => "$user", 
    password => "$passwd", 
    method => 'GET' 
); 

and then the get_attribute with 

$jmx->get_attribute('THREAD_COUNT');

**Comment by rhuss** [comment] 2019-09-27 07:32
This is a jmx4perl client issue and probably due how the underlying LWP library is dealing with basic authentication. Please open an issue over there (if not already), but as I'm currently super busy with other tasks, any help in fixing/evaluating the issue is highly appreciated.

Closing this here as it is really a jmx4perl client issue.

**Closed by rhuss** 2019-09-27 07:32 UTC
